version: 2

workflows:
  single-node:
    steps:
      -
        name: "test-nvidia"
        command: experiment.run_single_node
        params:
          command: run.sh
          container: tensorflow/tensorflow:1.13.1-gpu-py3
          machineType: "K80"
