version: 2

workflows:
  single-node:
    steps:
      -
        name: "test-nvidia"
        command: experiment.run_single_node
        params:
          command: bash run.sh
          container: aditya1e0/pytorch_nlp:2
          machineType: "K80"
